### ISSUE TITLE
test_wordprocessing fails

### ISSUE THREAD

**Issue by GoogleCodeExporter** [glenfant/openxmllib#12]
```
What steps will reproduce the problem?
1.  svn checkout http://openxmllib.googlecode.com/svn/trunk/ openxmllib
2.  python runalltests.py
3.  See below

What is the expected output? No errors


What version of the product are you using? On what operating system?

Linux workepdevel113 2.6.34.8-0.2-desktop #1 SMP PREEMPT 2011-04-06 18:11:26 
+0200 x86_64 x86_64 x86_64 GNU/Linux

openxmllib: Current trunk (2011-08-16), 

Python 2.6.5 (r265:79063, May  6 2011, 17:25:59) 
[GCC 4.5.0 20100604 [gcc-4_5-branch revision 160292]] on linux2

lxml: python-lxml-2.2.6-3.1.x86_64

Please provide any additional information below.

python runalltests.py 
F................F......
======================================================================
FAIL: Indexable text with properties
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/modwork_egs_d/_openxmllib/tests/test_presentation.py", line 30, in test_indexableText
    self.failUnless(word in itext, "%s was expected in %s" % (word, itext))
AssertionError: midword was expected in [u'em', u'false', u'Title', 
u'2009-06-28T15:04:04Z', u'one', u'four', u'Personnalis\xe9', u'Microsoft', 
u'Office', u'PowerPoint', u'mid', u'1', u'0', u'2', u'4', u'7', u'12.0000', 
u'three', u'presentation', u'Chapter', u'I', u'Gilles', u'Lenfant', u'two', 
u'2009-06-28T15:02:12Z', u'My', u'word', u'14', u'proud', u'item', u't']

======================================================================
FAIL: Indexable text with properties
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/modwork_egs_d/_openxmllib/tests/test_spreadsheet.py", line 29, in test_indexableText
    self.failUnless(word in itext, "%s was expected in %s" % (word, itext))
AssertionError: midword was expected in [u'false', u'is', u'mid', u'another', 
u'The', u'comments', u'of', u'the', u'document', u'myinfo4', u'sheet', 
u'myinfo3', u'myinfo2', u'sum', u'spreadsheet', u'0', u'spread', u'Microsoft', 
u'Macintosh', u'Excel', u'9', u'12.0000', u'keyword1', u'keyword2', u'A', 
u'2009-06-28T15:05:31Z', u'Gilles', u'Lenfant', u'2', u'fr-FR', u'myinfo1', 
u'a', u'word', u'this', u'2007-12-03T15:53:07Z', u'The', u'subject', u'of', 
u'the', u'document', u'The', u'title', u'of', u'the', u'document']

----------------------------------------------------------------------
Ran 24 tests in 0.114s

FAILED (failures=2)

```

Original issue reported on code.google.com by `h...@tbz-pariv.de` on 16 Aug 2011 at 12:36

**Comment by petri** [comment]
Duplicate, closing.

**Comment by petri** [comment]
Not sure if this is a duplicate or the original report indicating the midword issue, thus reopening.
