### ISSUE TITLE
tests fail

### ISSUE THREAD

**Issue by petri** [glenfant/openxmllib#16]
Traceback:

   (thirdparty)MacBook-Pro:tests petri$ python runalltests.py
   .........F....F.........
   ======================================================================
   FAIL: test_indexableText (test_presentation.PresentationTest)
   Indexable text with properties
   ----------------------------------------------------------------------
   Traceback (most recent call last):
     File "/Users/petri/Code/thirdparty/openxmllib/tests/test_presentation.py", line 30, in test_indexableText
       self.failUnless(word in itext, "%s was expected in %s" % (word, itext))
   AssertionError: midword was expected in [u'em', u'false', u'Title', u'2009-06-28T15:04:04Z', u'one', u'four', u'Personnalis\xe9', u'Microsoft', u'Office', u'PowerPoint', u'mid', u'1', u'0', u'2', u'4', u'7', u'12.0000', u'three', u'presentation', u'Chapter', u'I', u'Gilles', u'Lenfant', u'two', u'2009-06-28T15:02:12Z', u'My', u'word', u'14', u'proud', u'item', u't']

   ======================================================================
   FAIL: test_indexableText (test_spreadsheet.SpreadsheetTest)
   Indexable text with properties
   ----------------------------------------------------------------------
   Traceback (most recent call last):
     File "/Users/petri/Code/thirdparty/openxmllib/tests/test_spreadsheet.py", line 29, in test_indexableText
       self.failUnless(word in itext, "%s was expected in %s" % (word, itext))
   AssertionError: midword was expected in [u'false', u'is', u'mid', u'another', u'The', u'comments', u'of', u'the', u'document', u'myinfo4', u'sheet', u'myinfo3', u'myinfo2', u'sum', u'spreadsheet', u'0', u'spread', u'Microsoft', u'Macintosh', u'Excel', u'9', u'12.0000', u'keyword1', u'keyword2', u'A', u'2009-06-28T15:05:31Z', u'Gilles', u'Lenfant', u'2', u'fr-FR', u'myinfo1', u'a', u'word', u'this', u'2007-12-03T15:53:07Z', u'The', u'subject', u'of', u'the', u'document', u'The', u'title', u'of', u'the', u'document']

   ----------------------------------------------------------------------
   Ran 24 tests in 0.161s

   FAILED (failures=2)

**Comment by petri** [comment]
There are two words that the presentation test expects to be in indexableText ("midword" and "Microsoft Office PowerPoint"). Are these supposed to be found by indexableText? Same problem exists with spreadsheet test , where "midword" is not found by indexableText.

I checked the test documents and my guess is indexableText fails to extract "midword" because of formatting splits the word.

Upon closer inspection, this is probably a duplicate of #12, despite its misleading title.

**Comment by petri** [comment]
Looks like these failures were on purpose, to demonstrate a problem needing a fix: see 39b84c16c6a7138a2e50062bcad93ab410392523 . Putting this issue on hold until someone has time to dig into that midword issue.
